drop table public.comment cascade;
drop table public.blog cascade;
drop table public.reaction cascade;
drop table public.user cascade;

CREATE TABLE public.COMMENT(
	ID INT NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	CONTENT TEXT,
	CREATE_AT TIMESTAMP,
	BLOG_ID VARCHAR,
	AUTHOR_ID INT,
	CONSTRAINT PK_COMMENT PRIMARY KEY(ID) 
);

CREATE TABLE public.BLOG(
	ID INT NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	AUTHOR_ID INT,
	CREATE_AT TIMESTAMP,
	THUMBNAIL VARCHAR,
	HEADLINE VARCHAR(500),
	TRAILTEXT VARCHAR,
	CONTENT TEXT,
	CONSTRAINT PK_BLOG PRIMARY KEY(ID) 
);
CREATE TABLE public.REACTION(
	ID INT NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
	CREATE_AT TIMESTAMP,
	BLOG_ID VARCHAR,
	COMMENT_ID INT,
	AUTHOR_ID INT,
	CONSTRAINT PK_REACTION PRIMARY KEY(ID) 
);

CREATE TABLE public.USER (
	ID INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    fullname VARCHAR,
	address VARCHAR,
	job VARCHAR,
    dob VARCHAR,
    username VARCHAR,
    password VARCHAR,
    is_admin boolean DEFAULT false,
	CONSTRAINT PK_USER PRIMARY KEY(ID)
);
	

--
-- PostgreSQL database dump
--

-- Dumped from database version 14.4 (Ubuntu 14.4-1.pgdg20.04+1)
-- Dumped by pg_dump version 14.2

-- Started on 2022-07-10 12:41:40 +07

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4322 (class 0 OID 6659675)
-- Dependencies: 214
-- Data for Name: comment; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.comment(CONTENT ,CREATE_AT ,BLOG_ID, AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('update comment test cua bai post test', '2022-05-22 10:15:06.796153+00', 'blog/1', 10);
INSERT INTO public.comment(CONTENT ,CREATE_AT ,BLOG_ID, AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('test comment', '2022-06-20 20:32:20.168577+00', 'blog/2', 5);
INSERT INTO public.comment(CONTENT ,CREATE_AT ,BLOG_ID, AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('test comment again', '2022-06-20 20:32:42.10532+00', 'blog/2', 5);
INSERT INTO public.comment(CONTENT ,CREATE_AT ,BLOG_ID, AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ( 'test hehe', '2022-06-20 20:33:15.236251+00', 'blog/2', 5);
INSERT INTO public.comment(CONTENT ,CREATE_AT ,BLOG_ID, AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('sumthing', '2022-06-20 20:34:34.230999+00', 'blog/2', 5);
INSERT INTO public.comment(CONTENT ,CREATE_AT ,BLOG_ID, AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('Thú vị thật không?', '2022-06-21 01:21:25.194599+00', 'blog/2', 10);
INSERT INTO public.comment(CONTENT ,CREATE_AT ,BLOG_ID, AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('Mọi người giúp đỡ nhé', '2022-06-21 01:22:28.156438+00', 'blog/2',8);
INSERT INTO public.comment(CONTENT ,CREATE_AT ,BLOG_ID, AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('Ok anh bạn, tôi có thể giúp anh', '2022-06-21 01:23:20.960481+00', 'blog/2', 9);
INSERT INTO public.comment(CONTENT ,CREATE_AT ,BLOG_ID, AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('Vào đây nhé: https://github.com/', '2022-06-21 01:23:47.170378+00', 'blog/1', 10);
INSERT INTO public.comment(CONTENT ,CREATE_AT ,BLOG_ID, AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('hi', '2022-06-22 11:57:46.125298+00', 'blog/1', 2);
INSERT INTO public.comment(CONTENT ,CREATE_AT ,BLOG_ID, AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('ok bạn nha', '2022-06-22 13:26:04.394191+00', 'blog/1', 2);
INSERT INTO public.comment(CONTENT ,CREATE_AT ,BLOG_ID, AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('Xin chào bạn', '2022-06-22 13:26:45.791661+00', 'blog/1', 2);
INSERT INTO public.comment(CONTENT ,CREATE_AT ,BLOG_ID, AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('hey hey', '2022-06-24 16:20:24.685934+00', 'blog/1', 3);
INSERT INTO public.comment(CONTENT ,CREATE_AT ,BLOG_ID, AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('chào cậu', '2022-06-24 16:20:53.18751+00', 'blog/1', 4);
INSERT INTO public.comment(CONTENT ,CREATE_AT ,BLOG_ID, AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('hehehe', '2022-07-06 07:54:10.585113+00', 'blog/1', 5);




--
-- TOC entry 4320 (class 0 OID 6659584)
-- Dependencies: 212
-- Data for Name: post; Type: TABLE DATA; Schema: public; Owner: -
--


INSERT INTO public.BLOG(AUTHOR_ID ,CREATE_AT,THUMBNAIL ,HEADLINE, TRAILTEXT ,CONTENT) OVERRIDING SYSTEM VALUE VALUES (5, '2022-06-20 20:01:47.574161+00','https://firebasestorage.googleapis.com/v0/b/cloapedia-2df04.appspot.com/o/5399c3cf-27c5-4a59-a1fb-d9f0e9c1d5ea.jpg?alt=media', 'Chủ đề này sẽ rất thú vị nếu bạn thích','trail text', '<h3>aasas</h3><h3>as</h3><figure class="image"><img src="https://firebasestorage.googleapis.com/v0/b/cloapedia-2df04.appspot.com/o/0b2bfd9e-31ee-4ec7-b496-37d981b2cbaa.png?alt=media"></figure><p>assaas</p><p>&nbsp;</p><figure class="media"><div data-oembed-url="https://www.youtube.com/watch?v=jlzJNEc3JLc"><div style="position: relative; padding-bottom: 100%; height: 0; padding-bottom: 56.2493%;"><iframe src="https://www.youtube.com/embed/jlzJNEc3JLc" style="position: absolute; width: 100%; height: 100%; top: 0; left: 0;" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen=""></iframe></div></div></figure><p>&nbsp;</p>');
INSERT INTO public.BLOG(AUTHOR_ID ,CREATE_AT,THUMBNAIL ,HEADLINE, TRAILTEXT ,CONTENT) OVERRIDING SYSTEM VALUE VALUES (10, '2022-06-20 20:03:44.043937+00','https://firebasestorage.googleapis.com/v0/b/cloapedia-2df04.appspot.com/o/72c5e424-4503-4e94-9514-eb30ac8f41cc.jpg?alt=media', 'test nữa nè','trail text 2', 'test nữa');



--
-- TOC entry 4324 (class 0 OID 6659693)
-- Dependencies: 216
-- Data for Name: reaction; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.reaction(CREATE_AT ,BLOG_ID ,COMMENT_ID ,AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('2022-06-22 11:54:38.10964+00', 'blog/2',NULL, 1);
INSERT INTO public.reaction(CREATE_AT ,BLOG_ID ,COMMENT_ID ,AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('2022-06-22 11:55:01.720961+00', 'blog/2',NULL, 2);
INSERT INTO public.reaction(CREATE_AT ,BLOG_ID ,COMMENT_ID ,AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('2022-06-22 11:57:42.87093+00', 'blog/2',NULL, 3);
INSERT INTO public.reaction(CREATE_AT ,BLOG_ID ,COMMENT_ID ,AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('2022-06-22 13:25:56.893009+00', NULL,3, 4);
INSERT INTO public.reaction(CREATE_AT ,BLOG_ID ,COMMENT_ID ,AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('2022-06-22 13:26:41.12704+00', NULL,4, 5);
INSERT INTO public.reaction(CREATE_AT ,BLOG_ID ,COMMENT_ID ,AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('2022-06-24 16:20:42.734435+00', 'blog/1',NULL, 6);
INSERT INTO public.reaction(CREATE_AT ,BLOG_ID ,COMMENT_ID ,AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('2022-06-24 16:20:56.718172+00', 'blog/3',NULL, 7);
INSERT INTO public.reaction(CREATE_AT ,BLOG_ID ,COMMENT_ID ,AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('2022-07-06 07:54:15.706904+00', 'blog/4',NULL, 8);
INSERT INTO public.reaction(CREATE_AT ,BLOG_ID ,COMMENT_ID ,AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('2022-07-06 07:55:21.330748+00', 'blog/4',NULL, 9);
INSERT INTO public.reaction(CREATE_AT ,BLOG_ID ,COMMENT_ID ,AUTHOR_ID) OVERRIDING SYSTEM VALUE VALUES ('2022-07-06 08:06:25.470232+00', 'blog/5',NULL, 10);


--
-- TOC entry 4318 (class 0 OID 6659572)
-- Dependencies: 210
-- Data for Name: user; Type: TABLE DATA; Schema: public; Owner: -
--


INSERT INTO public."user"(fullname,address,job ,dob ,username ,password,is_admin) OVERRIDING SYSTEM VALUE VALUES ('Hoang Thi Truong',NULL,NULL, '12/02/2002', 'test4', '$2b$10$IehL4ShtGLCv5OAUUY7ELeyh2xrJBwc.DmNg0hmkXmMOphK1f5Cda', false);
INSERT INTO public."user"(fullname,address,job ,dob ,username ,password,is_admin) OVERRIDING SYSTEM VALUE VALUES ('Manh Hung Tien',NULL,NULL, '12/02/2002', 'test5', '$2b$10$9u6vSvL4Df0JhVlzFeaJi.32blRSoJrsA.w1vDcBIUdl/XF32DJI2', false);
INSERT INTO public."user"(fullname,address,job ,dob ,username ,password,is_admin) OVERRIDING SYSTEM VALUE VALUES ('Nguyen Huy Hoang',NULL,NULL, '12/02/2002', 'hhoang', '$2b$10$Vnw0j.qQWa/ap5JUGViiwexqqVYbyF9BqvAhqY.lQrn2iv/maaiIK', false);
INSERT INTO public."user"(fullname,address,job ,dob ,username ,password,is_admin) OVERRIDING SYSTEM VALUE VALUES ('Minh Lap',NULL,NULL, '12/02/2002', 'minhlap', '$2b$10$GRdmekQQMLY5i.dAmmMnzOaoFtLkOC7fvJ/IWjmqVNB.d/ZJH..P.', false);
INSERT INTO public."user"(fullname,address,job ,dob ,username ,password,is_admin) OVERRIDING SYSTEM VALUE VALUES ('Nguyen Hoang Tien',NULL,NULL, '12/02/2001', 'htien2', '$2b$10$EuwgrUkd2rO6czKdZn0HA.EjESm7I07Rgh0hGHjEy/Ojm//riCuNi', false);
INSERT INTO public."user"(fullname,address,job ,dob ,username ,password,is_admin) OVERRIDING SYSTEM VALUE VALUES ('Ngo Nhat Tho',NULL,NULL, '12/02/2001', 'htien3', '$2b$10$oHbZVlTGywSgyFea.hAFoOOwIY6gEFR7a0tsjOLu2Fu3hpaW3VecC', false);
INSERT INTO public."user"(fullname,address,job ,dob ,username ,password,is_admin) OVERRIDING SYSTEM VALUE VALUES ('Le Duc Tam',NULL,NULL, '12/02/2003', 'tamld', '$2b$10$3iwrwkqLJyWhMqN7bci6b.yYvaxlT.2jw5k6KXwNbicupDuS/Z6Xe', false);
INSERT INTO public."user"(fullname,address,job ,dob ,username ,password,is_admin) OVERRIDING SYSTEM VALUE VALUES ('staff1',NULL,NULL, '1/1/2000', 'staff1', '$2b$10$7xcP0dWZEW2TsgUPUQYeZ.bsiIObiKS7a.QbJtCGcZJlu.pNPbLYS', false);
INSERT INTO public."user"(fullname,address,job ,dob ,username ,password,is_admin) OVERRIDING SYSTEM VALUE VALUES ('Hoang Vinh',NULL,NULL, '12/02/2002', 'hvinh', '$2b$10$AyDNQxgV7i0HLnkUMjE2aOOz9CD3Jc0PNKivGQOG1AP8SeB9hJKbu', false);
INSERT INTO public."user"(fullname,address,job ,dob ,username ,password,is_admin) OVERRIDING SYSTEM VALUE VALUES ('leduc tam',NULL,NULL, '11/02/2001', 'godofwar', '$2a$10$1eY0TesxaS2Pd8SRh5ntdOCazK869VQCDK0AF/wE2fpMtUikUV5ye', false);




